### ISSUE TITLE
Kb analysis has stopped after change to title

### ISSUE THREAD

**Issue by varunsh-coder** [step-security/secure-workflows#1116]
`Not performing analysis as issue is not a valid KB issue`

https://github.com/step-security/secure-workflows/runs/8179731135?check_suite_focus=true#step:5:6

**Comment by varunsh-coder** [comment]
@Devils-Knight please investigate this.

**Comment by Devils-Knight** [comment]
The Bug was in the checksum used by `kBanalysis.yml` file for kBanalysis step, [This](https://github.com/step-security/secure-workflows/blob/03a07b65449688ebe9e517e4446b9f323bb194a0/.github/workflows/kbanalysis.yml#L30) checksum correspond to a [previous commit](https://api.github.com/repos/step-security/secure-workflows/commits/271e465ba8ae63db24252f69b0b10ff8bcdd1b45) made a month ago.

I think rest of the changes are fine, here is a reference for kBanalysis: [link](https://github.com/Devils-Knight/secure-workflows/issues/9)

> FIX: Use [app.stepsecurity.io](https://app.stepsecurity.io/) to update/add checksum to the `KBanalysis.yml` file.

**Comment by varunsh-coder** [comment]
Thanks @Devils-Knight for catching that!
