### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by arjundashrath** [step-security/secure-workflows#353]
https://github.com/arjundashrath/secure-workflows/runs/5226722991?check_suite_focus=true

**Comment by Devils-Knight** [comment]
@arjundashrath Tests are failing because PAT is not being fetched from Secrets.
https://github.com/step-security/secure-workflows/blob/418d6e16ec4b422bc1e23433e877bd27b17429fa/.github/workflows/test.yml#L31 
Set `PAT` secret in your environment variable to resolve this issue.
- View [here](https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository) to set secrets for action.
- View [here](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token#creating-a-token) to generate Personal Access Token.

[Here](https://github.com/Devils-Knight/secure-workflows/runs/5229906716?check_suite_focus=true) is the result of Action  after adding PAT.
